# Generated by Django 2.0 on 2021-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookn', models.CharField(default='Book Name', max_length=50)),
                ('authorn', models.CharField(default='Author Name', max_length=50)),
                ('bookp', models.IntegerField(default=123)),
                ('book_file', models.FileField(default='none.pdf', upload_to='media/book')),
            ],
        ),
    ]
