# Generated by Django 2.0 on 2021-03-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210331_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='none.pdf', upload_to='books/'),
        ),
    ]
